import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import Header from '@/compontents/header/Header'
import Footer from '@/compontents/footer/Footer'
import WhatsApp from '@/compontents/whatsapp/WhatsApp'

import './globals.scss'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'GWL',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='ru'>
            <body className={montserrat.className}>
                <main className='container'>
                    <Header />
                    {children}
                    <Footer />
                    <WhatsApp />
                </main>
            </body>
        </html>
    )
}
